name    'reidmv-nss'
version '0.0.1'
source 'https://github.com/reidmv/puppet-module-nss'
author 'Reid Vandewiele'
license 'Apache 2.0'
summary 'Module to manage NSSwitch entries'
description 'Ensurable type and provider for nsswitch.conf configuration'
project_page 'https://github.com/reidmv/puppet-module-nss'

dependency 'reidmv/augeasprovider', '>= 0.0.2'
